#####################################
# Config data for the plots of MROC #
#####################################
mroc:
  wind_direction:
    contour_map:
      min: 60
      max: 260
      ticks_num: 9
    time_series:
      min: 50
      max: 300
      tick_jump: 50
      hline:
        - 5
        - 6
        - 8
        - 9
        - 10

  wind_speed:
    contour_map:
      min: 2
      max: 18
      ticks_num: 9
    time_series:
      min: 3
      max: 19
      tick_jump: 3
      hline:
        -

  wind_gust:
    contour_map:
      min: 16
      max: 30
      ticks_num: 8
    time_series:
      min: 16
      max: 31
      tick_jump: 2
      hline:
        -

  temperature:
    contour_map:
      min: 16
      max: 30
      ticks_num: 8
    time_series:
      min: 16
      max: 31
      tick_jump: 2
      hline:
        -

  dewpoint:
    contour_map:
      min: 12
      max: 22
      ticks_num: 6
    time_series:
      min: 12
      max: 24
      tick_jump: 2
      hline:
        -

  pressure:
    contour_map:
      min: 29.90
      max: 30.06
      ticks_num: 0.02
    time_series:
      min: 29.90
      max: 30.07
      tick_jump: 0.02
      hline:
        -

#####################################
# Config data for the plots of MRLB #
#####################################
mrlb:
  wind_direction:
    contour_map:
      min: 60
      max: 260
      ticks_num: 9
    time_series:
      min: 50
      max: 250
      tick_jump: 50
      hline:
        - 5
        - 6
        - 8
        - 9
        - 10

  wind_speed:
    contour_map:
      min: 2
      max: 20
      ticks_num: 10
    time_series:
      min: 1
      max: 20
      tick_jump: 2
      hline:
        -

  wind_gust:
    contour_map:
      min: 16
      max: 32
      ticks_num: 9
    time_series:
      min: 16
      max: 33
      tick_jump: 2
      hline:
        -

  temperature:
    contour_map:
      min: 22
      max: 36
      ticks_num: 8
    time_series:
      min: 22
      max: 38
      tick_jump: 2
      hline:
        - 
  
  dewpoint:
    contour_map:
      min: 16
      max: 24
      ticks_num: 9
    time_series:
      min: 16
      max: 27
      tick_jump: 2
      hline:
        -

  pressure:
    contour_map:
      min: 29.74
      max: 29.91
      ticks_num: 0.02
    time_series:
      min: 29.74
      max: 29.91
      tick_jump: 0.02
      hline:
        -

#####################################
# Config data for the plots of MRLM #
#####################################
mrlm:
  wind_direction:
    contour_map:
      min: 60
      max: 260
      ticks_num: 9
    time_series:
      min: 50
      max: 300
      tick_jump: 50
      hline:
        - 1
        - 4
        - 7
        - 10

  wind_speed:
    contour_map:
      min: 2
      max: 10
      ticks_num: 9
    time_series:
      min: 2
      max: 10
      tick_jump: 1
      hline:
        -

  wind_gust:
    contour_map:
      min: 10
      max: 20
      ticks_num: 6
    time_series:
      min: 10
      max: 20
      tick_jump: 2
      hline:
        - 
  
  temperature:
    contour_map:
      min: 21
      max: 31
      ticks_num: 11
    time_series:
      min: 20
      max: 33
      tick_jump: 2
      hline:
        -

  dewpoint:
    contour_map:
      min: 20
      max: 26
      ticks_num: 7
    time_series:
      min: 18
      max: 27
      tick_jump: 2
      hline:
        -

  pressure:
    contour_map:
      min: 29.76
      max: 30.01
      ticks_num: 0.02
    time_series:
      min: 29.76
      max: 30.00
      tick_jump: 0.02
      hline:
        -

#####################################
# Config data for the plots of MRPV #
#####################################
mrpv:
  wind_direction:
    contour_map:
      min: 60
      max: 260
      ticks_num: 9
    time_series:
      min: 50
      max: 300
      tick_jump: 50
      hline:
        - 5
        - 6
        - 8
        - 9
        - 10

  wind_speed:
    contour_map:
      min: 2
      max: 18
      ticks_num: 9
    time_series:
      min: 3
      max: 19
      tick_jump: 3
      hline:
        -

  wind_gust:
    contour_map:
      min: 18
      max: 32
      ticks_num: 8
    time_series:
      min: 16
      max: 31
      tick_jump: 2
      hline:
        -

  temperature:
    contour_map:
      min: 16
      max: 28
      ticks_num: 7
    time_series:
      min: 16
      max: 29
      tick_jump: 2
      hline:
        -

  dewpoint:
    contour_map:
      min: 12
      max: 20
      ticks_num: 5
    time_series:
      min: 12
      max: 22
      tick_jump: 2
      hline:
        -

  pressure:
    contour_map:
      min: 29.92
      max: 30.08
      ticks_num: 0.02
    time_series:
      min: 29.92
      max: 30.09
      tick_jump: 0.02
      hline:
        - 